name: Deploy Docs

on:
  push:
    branches:
      - main
    pull_requests:

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Deploy Docs
        uses: intergiro/vuepress-deploy@fix_git_repo # Update back to jenkey2011/vuepress-deploy@master once merged
        env:
          GITHUB_DEPLOY: true
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_REPO: mitre/saf-training-current
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: pnpm run docs:build
          BUILD_DIR: src/.vuepress/dist/
