name: Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          GITHUB_DEPLOY: true
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: mitre/saf-training-current
          TARGET_BRANCH: main
          BUILD_SCRIPT: pnpm run docs:build
          BUILD_DIR: src/.vuepress/dist
